package org.weso.snoicd.indexer.io;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.weso.snoicd.core.Concept;

import java.io.File;
import java.io.IOException;
import java.util.List;

/**
 * This class loads the file generated by the crawler in a List of Concepts.
 */
public class ConceptsLoader {

    private List<Concept> concepts;
    private String pathname;

    /**
     * Initilizes the object and starts the task of loading concepts.
     *
     * @param pathname to the file produced by the crawler.
     */
    public ConceptsLoader(String pathname) {
        this.pathname = pathname;
        loadConceptsInMemory();
    }

    /**
     * Gets a List of type concept where all the concepts generated by the crawler are.
     *
     * @return a List of type concept where all the concepts generated by the crawler are.
     */
    public List<Concept> getConcepts() {
        return this.concepts;
    }

    /**
     * Loads the json file produced by the crawler and maps the json entities to a list of concepts.
     */
    private void loadConceptsInMemory() {
        ObjectMapper mapper = new ObjectMapper();
        try {
            concepts = mapper.readValue(
                    new File(pathname),
                    mapper.getTypeFactory().constructCollectionType(List.class, Concept.class)
            );
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
